name: agentic-framework
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.111.0
      - uvicorn==0.30.1
      - httpx==0.27.0
      - python-dotenv==1.0.1
      - PyYAML==6.0.1
      - langchain==0.1.0
      - langchain-openai==0.0.5
      - langchain-community==0.0.10
      - pydantic==2.5.3
